Courses Table Component and Tests
ucsb-cs156-w22/team04-w22-6pm-courses pull request #37
Opened 2022-03-08 03:46 UTC by ShivaanshK

2022-03-08 18:30 UTC, Peake2 requested changes
2 Small fixes and some unused imports

2022-03-08 18:30 UTC, Peake2 commented on frontend/src/main/components/Courses/CoursesTable.js
> +        course.description = course.description.slice(0, 100) + '...'
If the description is less than 100 characters, it won't be cut but will still get a '...'

2022-03-08 18:30 UTC, Peake2 commented on frontend/src/main/components/Courses/CoursesTable.js
> +import { useTable, useSortBy } from 'react-table'
Unused import

2022-03-08 18:30 UTC, Peake2 commented on frontend/src/main/components/Courses/CoursesTable.js
> +import { Table, Button } from "react-bootstrap";
Unused import

2022-03-08 18:30 UTC, Peake2 commented on frontend/src/tests/components/Courses/CoursesTable.test.js
> +    test("click on a header and a sort caret should appear", async () => {
IDK if it was implemented by you, but testing sort by description on threeCourses on storybook does not sort it correctly

2022-03-08 18:30 UTC, Peake2 commented on frontend/src/tests/components/Courses/CoursesTable.test.js
> +import { render, waitFor, fireEvent } from "@testing-library/react";
fireEvent is unused import

2022-03-08 22:13 UTC, Peake2 approved these changes
Review 2: LGTM

2022-03-08 23:38 UTC, bzamora020 approved these changes
Looks good to me!

2022-03-08 23:53 UTC, Peake2 commented
> Looks good to me!

Could you merge and assign points please? "The base branch restricts merging to authorized users."

2022-03-09 02:22 UTC, merged

2022-03-09 02:22 UTC, bzamora020 commented
Thanks! This is a 10 points issue